import Head from 'next/head'
import Image from 'next/image'
import { Inter, Roboto, Open_Sans } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header/Header'

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Video Downloader</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
